# Generated by Django 4.2.1 on 2023-06-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_usuario_id_user_alter_usuario_telefono_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoriaId_prod',
            new_name='categoriaId',
        ),
    ]
