# Generated by Django 4.2.1 on 2023-06-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_rename_categoriaid_prod_producto_categoriaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=15)),
            ],
        ),
    ]
