# Generated by Django 4.2.1 on 2023-06-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tienda", "0004_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagenUrl_prod",
            field=models.ImageField(upload_to="imagenesProducto"),
        ),
    ]
